apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturersr-expressapi
  namespace: manufacturersr-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp-quorum
    git: "ssh://git@github.com/srinivasansankaran/blockchain-automation-framework.git"
    ref: "develop"
  releaseName: manufacturersrquorum-expressapi
  values:
    nodeName: manufacturersr-expressapi
    metadata:
      namespace: manufacturersr-quo
    replicaCount: 1
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/manufacturersr-quo/smartContracts
      serviceaccountname: vault-auth
      keyname: General
      role: vault-role
      authpath: quorummanufacturersr
    images:
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    expressapp:
      serviceType: ClusterIP
      image: index.docker.io/hyperledgerlabs/supplychain_quorum:express_app_latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        geth_address: http://manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com:15221
        node_subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
        node_organization: manufacturersr
        node_organization_unit: manufacturersr
        protocol: raft
    proxy:
      provider: ambassador
      name: manufacturersr
      type: quorum
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      peer_name: manufacturersr
