apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturersrmanufacturersrtessera
  namespace: manufacturersr-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturersrmanufacturersrtessera
  helmVersion: v3
  chart:
    git: ssh://git@github.com/srinivasansankaran/blockchain-automation-framework.git
    ref: develop
    path: platforms/quorum/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: manufacturersr-quo
      labels:
    images:
      node: quorumengineering/quorum:2.5.0
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:0.10.4
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: manufacturersr
      status: default
      consensus: raft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 8443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/manufacturersr-quo/crypto/manufacturersr
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorummanufacturersr
    tessera:
      dburl: "jdbc:mysql://manufacturersr:3306/demodb"
      dbusername: demouser
      url: "https://manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com:8443"
      othernodes:
        - url: https://carriersr.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
        - url: https://manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICI1Mjc5N2MxY2M5ZTI3MWYxODU5YjA2Njg1YWQ2YTAzNGQ0MTJjNzNlIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjY2OTQ3MTZmNTA3MjRkNzYxZmFmZjZiN2I4NjM0MGE2MjlhMmUyZDciOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfQogICAgfSwKICAgICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImNvbmZpZyI6IHsKICAgICAgICAiYnl6YW50aXVtQmxvY2siOiAxLAogICAgICAgICJjaGFpbklkIjogMTAsCiAgICAgICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgICAgICJlaXAxNTBCbG9jayI6IDEsCiAgICAgICAgImVpcDE1MEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICAgICAiZWlwMTU1QmxvY2siOiAwLAogICAgICAgICJlaXAxNThCbG9jayI6IDEsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZSwKICAgICAgICAicGV0ZXJzYnVyZ0Jsb2NrIjogMCwKICAgICAgICAicmFmdFNlY29uZHMiOiB0cnVlLAogICAgICAgICJ0eG5TaXplTGltaXQiOiAxMjgKICAgIH0sCiAgICAiZGlmZmljdWx0eSI6ICIweDAiLAogICAgImV4dHJhRGF0YSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImdhc0xpbWl0IjogIjB4RTAwMDAwMDAwMCIsCiAgICAibWl4aGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjQ3NTcyNjE2YzY1Nzg3MzY1NjQ2YzY1NzgiLAogICAgIm5vbmNlIjogIjB4MCIsCiAgICAicGFyZW50SGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgInRpbWVzdGFtcCI6ICIweDAwIgp9
    staticnodes: 
      [
    "enode://ff73e83a33e8617eb43b9699f511b432b18a16b0e79a7db695d424ea3a11783996c4342a618b80a9711281c7d37ef58060a7bee557ba67c145433a64b38b9faf@carriersr.rc.dev2.aws.blockchaincloudpoc-develop.com:15210?discport=0&raftport=15213",
    "enode://e591908aa15a984e43fd24cd76602d9d712dfe8789ac0acbc7d6b221d7ce7d4ab767a5bdf7ed58dd489a0956a177efa01018891f4c68d2cb22c85cdfcf2fc7f3@manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com:15220?discport=0&raftport=15223"
]
    proxy:
      provider: "ambassador"
      external_url: manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 8443
      rpcport: 15221
      quorumport: 15220
  
      portRaft: 15223
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
