apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturersrmanufacturersrconstellation
  namespace: manufacturersr-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturersrmanufacturersrconstellation
  helmVersion: v3
  chart:
    git: ssh://git@github.com/srinivasansankaran/blockchain-automation-framework.git
    ref: develop
    path: platforms/quorum/charts/node_constellation
  values:
    replicaCount: 1
    metadata:
      namespace: manufacturersr-quo
      labels: 
    images:
      node: quorumengineering/quorum:2.5.0
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      constellation: quorumengineering/constellation:0.3.2
    node:
      name: manufacturersr
      status: default
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagepullsecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: true/false
      ports:
        rpc: 8546
        raft: 50401
        constellation: 9001
        quorum: 21000
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/manufacturersr-quo/crypto/manufacturersr
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorummanufacturersr
    genesis: ewogICAgImNvbmZpZyI6IHsKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImVpcDE1MEJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgICAgICJlaXAxNTVCbG9jayI6IDAsCiAgICAgICAgImVpcDE1OEJsb2NrIjogMCwKICAgICAgICAiYnl6YW50aXVtQmxvY2siOiAxLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiaXN0YW5idWwiOiB7CiAgICAgICAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAgICAgICAicG9saWN5IjogMCwKICAgICAgICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgICAgIH0sCiAgICAgICAgInR4blNpemVMaW1pdCI6IDEyOCwKICAgICAgICAibWF4Q29kZVNpemUiOiAxMjgsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZQogICAgfSwKICAgICJub25jZSI6ICIweDAiLAogICAgInRpbWVzdGFtcCI6ICIweDVmYjRmNGFjIiwKICAgICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg2ZmVhOTRhMTc5Yzc0ODYyZGI0YjIwZTc0NGE3OGE2NGVmZDczNjk4YWM3ZTE0OTRiMDkzMDA5OTM3Mjc2ZTY3OGRiYzk1Yjc1ZmJjNWNjNTE4ZmIwMDdkYjg0MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjMCIsCiAgICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgICAiZGlmZmljdWx0eSI6ICIweDEiLAogICAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAgICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImFsbG9jIjogewogICAgICAgICJhMTc5Yzc0ODYyZGI0YjIwZTc0NGE3OGE2NGVmZDczNjk4YWM3ZTE0IjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgICAgICB9LAogICAgICAgICJiMDkzMDA5OTM3Mjc2ZTY3OGRiYzk1Yjc1ZmJjNWNjNTE4ZmIwMDdkIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgICAgICB9CiAgICB9LAogICAgIm51bWJlciI6ICIweDAiLAogICAgImdhc1VzZWQiOiAiMHgwIiwKICAgICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://60c4f1e79c4404424bf4e4b045160e6b348391f623b8c0cc269083213187be802f54e54a9f94830f8ba98867c3d770db23adcb83e352bd9e959b189ec70f788b@carriersr.rc.dev2.aws.blockchaincloudpoc-develop.com:15210?discport=0",
    "enode://5b8474fbc16c340675728c3a3cd941f9d024fb530a847b9b5cacfda30f04154981cfc651a09960ff5c5e7f34021ebe88fa2f9ac78614e6a4317786c851e0c70a@manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com:15220?discport=0"
]
    constellation:
      url: https://manufacturersr.rc.dev2.aws.blockchaincloudpoc-develop.com:15022/
      storage: "bdb:/etc/quorum/qdata/database"
      tls: "strict"
      othernodes: ['http://carriersr.test.quorum.blockchaincloudpoc.com:15012']
      trust: "tofu"
    proxy:
      provider: "ambassador"
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      rpcport: 15221
      quorumport: 15220
      portConst: 15022
      portRaft: 15223
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
