apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carriersr-springboot
  namespace: carriersr-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carriersr-springboot
  chart:
    path: examples/supplychain-app/charts/springbootwebserver
    git: "ssh://git@github.com/srinivasansankaran/blockchain-automation-framework.git"
    ref: "develop"
  values:
    nodeName: carriersr-springboot
    replicas: 1
    metadata:
      namespace: carriersr-ent
      type: cordaenterprise
    image:
      containerName: index.docker.io/hyperledgerlabs/supplychain_corda:springboot_0.4.2.0
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
    smartContract:
      JAVA_OPTIONS : -Xmx512m
    volume:
      mountPath: /opt/corda
    nodeConf:
      node: carriersr
      nodeRpcPort: 10003
      nodeRpcAdminPort: 10005
      controllerName: Controller
      trustStorePath: /opt/corda/certificates/sslkeystore.jks
      trustStoreProvider: jks
      legalName: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      devMode: false
      useHTTPS: true
      useSSL: false
      tlsAlias: cordaclienttls
      ssl:
        certificatesDirectory: na-ssl-false
        sslKeystoreFileName: na-ssl-false
        ssltruststore: na-ssl-false
    credentials:
      rpcUser: carriersr
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      provisioner: kubernetes.io/aws-ebs
      memory: 512Mi
      name: awsstorageclass
      parameters:
        type: gp2
        encrypted: "true"
      annotations: {}
    web:
      targetPort: 20001
      port: 20001
    service:
      type: NodePort
      annotations: {}
    networkservices:
      networkmap: networkmapsr
      doorman: idmansr
    vault:
      address: "http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001"
      role: vault-role
      authpath: cordaentcarriersr
      serviceaccountname: vault-auth
      rpcusersecretprefix: secret/carriersr/carriersr/credentials
      keystoresecretprefix: secret/carriersr/carriersr/credentials
      certsecretprefix: secret/carriersr/carriersr/certs
    node:
      readinesscheckinterval: 10
      readinessthreshold: 15
    deployment:
      annotations: {}
    pvc:
      annotations: {}
