---
# Task to transfer did and seed vaules from one secret engine to another

# Transfer DID and Seed Values between Vaults
- name: "Transfer DID and Seed Values between Vaults"
  shell: |
    domain_genesis={{ genesis.domain | indent(width=8) | b64encode }};
    echo $domain_genesis | base64 -d | sed -e 's/[ \t]*//' >> domain_transactions_genesis;
    head -n 1 domain_transactions_genesis | jq -j ".txn.data.alias" | sed -n 1'p' | tr '-' '\n' > alias.txt;
    
    admin_org=$(head -n 1 alias.txt);
    admin_role=$(tail -n 1 alias.txt)s;
    alias=$(head -n 1 domain_transactions_genesis | jq -j ".txn.data.alias");    

    admin_seed=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$admin_org/$admin_role/$alias/identity/private | jq -j ".data.seed")
    admin_did=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$admin_org/$admin_role/$alias/identity/public | jq -j ".data.did")

    new_org={{ organization }}
    new_org_role="stewards";
    new_org_alias={{ stewardItem.name }}

    trustee_seed=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/trustees/$new_org-trustee/identity/private | jq -j ".data.seed")
    trustee_did=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/trustees/$new_org-trustee/identity/public | jq -j ".data.did")
    trustee_verkey=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/trustees/$new_org-trustee/node/public/verif_keys | jq -j ".data.\"verification-key\"")

    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"seed": "'"$admin_seed"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/admin/private    
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"did": "'"$admin_did"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/admin/public
    
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"seed": "'"$trustee_seed"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/trustee/private    
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"did": "'"$trustee_did"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/trustee/public
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"verkey": "'"$trustee_verkey"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/trustee/node

    rm domain_transactions_genesis;
    rm alias.txt;    
  loop: "{{ services.stewards }}"
  when: services.stewards is defined
  loop_control:
    loop_var: stewardItem

    
